---
# tasks file for rhelonboard_util

- name: Identify RHEL Platforms
  gather_facts: true
  hosts: all
  tasks:
    - name: Print RHEL Details
      debug:
        msg:
        - "================================="
        - "Hostname   : {{ ansible_facts['nodename'] }}"
        - "IP Address : {{ ansible_facts['eth0']['ipv4']['address'] }}"
        - "OS Type    : {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} "
        - "================================="