---
# tasks file for hostname_change

- name: Hostname Change
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Hello World
      debug:
        msg: "this is {{ansible_facts['eth0']['ipv4']['address']}}"
    - name: Match
      debug:
        msg: "this is my name {{ lookup('csvfile', {{ansible_facts['eth0']['ipv4']['address']}} + ' file=hostlookup.csv delimiter=, col=1') }}"