---
# tasks file for hostname_change

- name: Hostname Change
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Hello World
      debug:
        msg: "this is {{ansible_facts['eth0']['ipv4']['address']}}"
    - name: Get Hostname
      set_fact:
        instance_hostname: "{{ lookup('csvfile', ansible_facts['eth0']['ipv4']['address'] + ' file=hostlookup.csv delimiter=, col=1') }}"
    - name:
      debug:
        msg: "this is my name {{instance_hostname}}"
    - name: Set Hostname
      ansible.builtin.hostname:
        name: "{{instance_hostname}}"
        use: systemd
    - name: Get NTP Details
      ansible.builtin.command: chronyc tracking | grep Reference | awk '{print $5}'
      register: myresults

    - name: Get NTP Details
      debug:
        msg : "This is a valid NTP address {{myresults}}"
      when: myresults is regex("\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")

