---
# tasks file for hostname_change

- name: Hostname Change
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Hello World
      debug:
        msg: "this is {{ansible_facts['eth0']['ipv4']['address']}}"
