---
# tasks file for hostname_change

- name: Hostname Change
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Hello World
      debug:
        msg: "Hello World!!!"
        var: ansible_facts