---
# tasks file for ntp_util

- name: Hostname Change
  gather_facts: true
  hosts: all
  become: yes
  tasks:

    - name: Get NTP Details
      shell: "chronyc tracking | grep Reference | awk '{print $5}'"
      register: ntpcheckresults

    - name: Check NTP Details (Success)
      debug:
        msg: 
        - "================================="
        - "Check NTP Details"
        - "Hostname   : {{ ansible_facts['nodename'] }}"
        - "IP Address : {{ ansible_facts['eth0']['ipv4']['address'] }}"
        - "OS Type    : {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} "
        - "NTP Check  : Successful"
        - "NTP Result : {{ntpcheckresults['stdout']}}"
      when: ntpcheckresults['stdout'] is regex("\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")

    - name: Check NTP Details (Failed)
      debug:
        msg: 
        - "================================="
        - "Check NTP Details"
        - "Hostname   : {{ ansible_facts['nodename'] }}"
        - "IP Address : {{ ansible_facts['eth0']['ipv4']['address'] }}"
        - "OS Type    : {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} "
        - "NTP Check  : Failed"
        - "NTP Result : {{ntpcheckresults['stdout']}}"
      when: not ntpcheckresults['stdout'] is regex("\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")

    