---
# tasks file for hostname_util

- name: Hostname Change
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Lookup Instance Hostname
      set_fact:
        instance_hostname: "{{ lookup('csvfile', ansible_facts['eth0']['ipv4']['address'] + ' file=hostlookup.csv delimiter=, col=1') }}"
      when: not ansible_facts['nodename'] is regex("^SG.+\d{3}$")
      
    - name: Set Hostname
      ansible.builtin.hostname:
        name: "{{instance_hostname}}"
        use: systemd
      when: not ansible_facts['nodename'] is regex("^SG.+\d{3}$")

    - name: Set Hostname Details
      debug:
        msg: 
        - "================================="
        - "Set Hostname Details"
        - "Old Hostname : {{ ansible_facts['nodename'] }}"
        - "New Hostname : {{instance_hostname}} "
        - "IP Address : {{ ansible_facts['eth0']['ipv4']['address'] }}"
        - "OS Type    : {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} "
        - "================================="
      when: not ansible_facts['nodename'] is regex("^SG.+\d{3}$")
